//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateStep
    {
        public int CandidateID { get; set; }
        public Nullable<bool> StepOne { get; set; }
        public Nullable<bool> StepTwo { get; set; }
        public Nullable<bool> StepThree { get; set; }
        public Nullable<bool> StepFour { get; set; }
        public Nullable<bool> StepFive { get; set; }
        public Nullable<bool> StepSix { get; set; }
        public Nullable<bool> StepSeven { get; set; }
        public Nullable<bool> StepEight { get; set; }
    }
}
