//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.EduDetails = new HashSet<EduDetail>();
            this.Interviews = new HashSet<Interview>();
            this.NotificationDetails = new HashSet<NotificationDetail>();
            this.SkillDetails = new HashSet<SkillDetail>();
        }
    
        public int CandidateID { get; set; }
        public string CName { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public string BloodGroupID { get; set; }
        public Nullable<int> MartialStatusID { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string LandlineNo { get; set; }
        public string CellNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> DomicileCityID { get; set; }
        public Nullable<int> NationalityCountryID { get; set; }
        public string Objective { get; set; }
        public Nullable<int> CImage { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GenderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EduDetail> EduDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationDetail> NotificationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillDetail> SkillDetails { get; set; }
    }
}
