//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EduDetail
    {
        public int EduID { get; set; }
        public Nullable<int> DegreeLevelID { get; set; }
        public string ObtainedMark { get; set; }
        public string TotalMark { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Institution { get; set; }
        public string MajorSubject { get; set; }
        public int CandidateID { get; set; }
        public string Percentage { get; set; }
        public string CGPA { get; set; }
        public string PassingYear { get; set; }
        public string DegreeTitle { get; set; }
        public string OtherInstitute { get; set; }
        public Nullable<bool> InProgress { get; set; }
        public Nullable<int> DegreeTypeID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual EduDegreeLevel EduDegreeLevel { get; set; }
    }
}
