//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public long PEmailID { get; set; }
        public string ToAddress { get; set; }
        public string CCAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<int> EmailTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public string Remarks { get; set; }
    }
}
