//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int InterviewID { get; set; }
        public string Title { get; set; }
        public int CandidateID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Job Job { get; set; }
    }
}
