//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobDetail()
        {
            this.Interviews = new HashSet<Interview>();
        }
    
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> LocID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CompanyName { get; set; }
        public string Experience { get; set; }
        public string ExperienceAndQualification { get; set; }
        public string PositionPurpose { get; set; }
        public Nullable<int> CatagoryID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SpecificRequirement { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public string DepatmentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interviews { get; set; }
    }
}
