//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscellaneousDetail
    {
        public int PMiscellaneousID { get; set; }
        public string CrimanalRecord { get; set; }
        public string WorkingRelative { get; set; }
        public Nullable<System.DateTime> DateJoining { get; set; }
        public Nullable<System.DateTime> DateLeavig { get; set; }
        public string EmploymentNo { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string ReasonLeaving { get; set; }
        public string TotalExp { get; set; }
        public string CementExp { get; set; }
        public Nullable<int> NoticeTime { get; set; }
        public Nullable<long> CandidateID { get; set; }
        public Nullable<bool> WorkedBefore { get; set; }
        public Nullable<int> HearAboutJobID { get; set; }
    }
}
