//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDetail
    {
        public int NotifyID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<bool> JobStatus { get; set; }
        public Nullable<int> InterviewID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
