//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceDetail
    {
        public int RefID { get; set; }
        public string RefName { get; set; }
        public string RefDesignation { get; set; }
        public string RefEmail { get; set; }
        public string RefContact { get; set; }
        public int CandidateID { get; set; }
    }
}
