//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AppliedJob
    {
        public Nullable<int> CandidateID { get; set; }
        public int CJobID { get; set; }
        public Nullable<System.DateTime> CJobDate { get; set; }
        public string CName { get; set; }
        public Nullable<int> JobID { get; set; }
        public string JobTitle { get; set; }
    }
}
