//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AppliedJob
    {
        public int CandidateID { get; set; }
        public int CJobID { get; set; }
        public Nullable<System.DateTime> CJobDate { get; set; }
        public string CName { get; set; }
        public Nullable<int> JobID { get; set; }
        public string JobTitle { get; set; }
        public string SpecificRequirement { get; set; }
        public string PositionPurpose { get; set; }
        public string ExperienceAndQualification { get; set; }
        public string Experience { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LocID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> CatagoryID { get; set; }
        public string CatName { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string JStatusName { get; set; }
        public string CVName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> HasCV { get; set; }
        public string CellNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DepatmentName { get; set; }
        public string SubDepartmentName { get; set; }
        public string FatherName { get; set; }
        public string CNICNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> CandidateCityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> DomicileCityID { get; set; }
        public string DomicileCityName { get; set; }
        public Nullable<double> TotalExp { get; set; }
        public Nullable<double> Cement { get; set; }
    }
}
