//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Candidate_Miscellaneous
    {
        public int PMiscellaneousID { get; set; }
        public string CrimanalRecord { get; set; }
        public string WorkingRelative { get; set; }
        public Nullable<System.DateTime> DateJoining { get; set; }
        public Nullable<System.DateTime> DateLeavig { get; set; }
        public string EmploymentNo { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string ReasonLeaving { get; set; }
        public Nullable<int> NoticeTime { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public string CName { get; set; }
        public string CNICNo { get; set; }
        public string WorkedBefore { get; set; }
        public Nullable<int> HearAboutJobID { get; set; }
        public string HearAboutSource { get; set; }
        public string CrimeDetail { get; set; }
        public string WorkingRelativeName { get; set; }
        public string WorkingRelativeRelation { get; set; }
        public string WorkingRelativeDepartment { get; set; }
        public string WorkingRelativeDesignation { get; set; }
        public string WorkingRelativeLocation { get; set; }
        public string InterviewedBefore { get; set; }
        public Nullable<System.DateTime> InterviewedDate { get; set; }
        public string InterviewedLocation { get; set; }
        public string AppliedPosition { get; set; }
        public string DisabilityDetail { get; set; }
        public string Disability { get; set; }
        public string HearAboutDetail { get; set; }
        public Nullable<bool> InternshipRequirement { get; set; }
        public string InternshipDuration { get; set; }
        public Nullable<int> ExpectedSalary { get; set; }
        public string MGSalary { get; set; }
        public Nullable<bool> UploadCV { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string BGroupName { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public string MartialStatusName { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public string ReligionName { get; set; }
        public Nullable<double> TotalExp { get; set; }
        public Nullable<double> CementExp { get; set; }
        public string LinkedInLink { get; set; }
        public string WorkingRelativeCompanyName { get; set; }
        public Nullable<int> InterviewStatusID { get; set; }
        public string WorkedBeforeCompanyName { get; set; }
        public Nullable<bool> WorkedBeforeCurrentlyWorking { get; set; }
        public string InterviewStatusName { get; set; }
        public string InterviewBeforeCompanyName { get; set; }
        public Nullable<int> NoticeTimeID { get; set; }
    }
}
