//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Candidate_Skills
    {
        public string Description { get; set; }
        public string Title { get; set; }
        public int SkillID { get; set; }
        public Nullable<int> SLevelID { get; set; }
        public string SkillLevelName { get; set; }
        public int CandidateID { get; set; }
        public string CName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
