//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JobDetail
    {
        public int JobID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> LocID { get; set; }
        public string LocName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CompanyName { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public string DepatmentName { get; set; }
        public string PositionPurpose { get; set; }
        public string SpecificRequirement { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> CatagoryID { get; set; }
        public string CatName { get; set; }
        public string ExperienceAndQualification { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string JStatusName { get; set; }
        public string SubDepartmentName { get; set; }
    }
}
