//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UserCandidate
    {
        public int CandidateID { get; set; }
        public string CName { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string RetypePassword { get; set; }
        public Nullable<int> UserStage { get; set; }
        public string Email { get; set; }
        public Nullable<bool> HaveExperience { get; set; }
        public Nullable<int> AppliedAs { get; set; }
        public Nullable<bool> HasCV { get; set; }
    }
}
