//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRM_Candidate
    {
        public string CName { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string BGroupName { get; set; }
        public Nullable<int> MartialStatusID { get; set; }
        public string MartialStatusName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public string LandlineNo { get; set; }
        public string CellNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> DomicileCityID { get; set; }
        public string DimicileCityName { get; set; }
        public Nullable<int> NationalityCountryID { get; set; }
        public string NationalityCountryName { get; set; }
        public string Objective { get; set; }
        public Nullable<int> CImage { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string GenderName { get; set; }
        public Nullable<int> AppliedAs { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ReligionName { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<bool> HaveExperience { get; set; }
        public Nullable<int> AreaOfInterestID { get; set; }
        public string AreaOfInterestName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CatName { get; set; }
        public string OtherCityName { get; set; }
        public Nullable<int> SalutationID { get; set; }
        public string SalutationName { get; set; }
        public string OtherAreaName { get; set; }
        public string CVName { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<bool> WorkPermitYes { get; set; }
        public Nullable<bool> WorkPermitNo { get; set; }
        public string OtherDomicileCityName { get; set; }
        public string OtherPakistaniCityName { get; set; }
        public string Tehsil { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> PMiscellaneousID { get; set; }
        public string CrimanalRecord { get; set; }
        public string WorkingRelative { get; set; }
        public Nullable<System.DateTime> DateLeavig { get; set; }
        public string EmploymentNo { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string ReasonLeaving { get; set; }
        public Nullable<int> NoticeTime { get; set; }
        public string WorkedBefore { get; set; }
        public string HearAboutSource { get; set; }
        public Nullable<int> HearAboutJobID { get; set; }
        public string CrimeDetail { get; set; }
        public string WorkingRelativeName { get; set; }
        public string WorkingRelativeRelation { get; set; }
        public string WorkingRelativeDepartment { get; set; }
        public string WorkingRelativeDesignation { get; set; }
        public string WorkingRelativeLocation { get; set; }
        public string InterviewedBefore { get; set; }
        public Nullable<System.DateTime> InterviewedDate { get; set; }
        public string InterviewedLocation { get; set; }
        public string AppliedPosition { get; set; }
        public string DisabilityDetail { get; set; }
        public string Disability { get; set; }
        public Nullable<bool> InternshipRequirement { get; set; }
        public string HearAboutDetail { get; set; }
        public string InternshipDuration { get; set; }
        public Nullable<int> ExpectedSalary { get; set; }
        public string MGSalary { get; set; }
        public Nullable<bool> UploadCV { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<int> MiscellaneousBloodGroupID { get; set; }
        public Nullable<int> MiscellaneousMaritalStatusID { get; set; }
        public string MiscellaneousBloodGroupName { get; set; }
        public string MiscellaneousMaritalStatusName { get; set; }
        public Nullable<int> MiscellaneousReligionID { get; set; }
        public string MiscellaneousReligionName { get; set; }
        public Nullable<double> TotalExp { get; set; }
        public Nullable<double> CementExp { get; set; }
        public string LinkedInLink { get; set; }
        public string WorkingRelativeCompanyName { get; set; }
        public Nullable<int> InterviewStatusID { get; set; }
        public string WorkedBeforeCompanyName { get; set; }
        public Nullable<bool> WorkedBeforeCurrentlyWorking { get; set; }
        public string InterviewStatusName { get; set; }
        public string InterviewBeforeCompanyName { get; set; }
        public Nullable<int> NoticeTimeID { get; set; }
        public Nullable<int> StrengthID { get; set; }
        public string Strengths { get; set; }
        public string AreaOfImprovement { get; set; }
        public string MeetRequirements { get; set; }
        public string CandidateStrengthObjectives { get; set; }
        public int CandidateID { get; set; }
    }
}
