//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSCORE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRM_CandidateSimple
    {
        public int CandidateID { get; set; }
        public string CName { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNICNo { get; set; }
        public Nullable<int> BloodGroupID { get; set; }
        public string BGroupName { get; set; }
        public Nullable<int> MartialStatusID { get; set; }
        public string MartialStatusName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public string LandlineNo { get; set; }
        public string CellNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> DomicileCityID { get; set; }
        public string DimicileCityName { get; set; }
        public Nullable<int> NationalityCountryID { get; set; }
        public string NationalityCountryName { get; set; }
        public string Objective { get; set; }
        public Nullable<int> CImage { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string GenderName { get; set; }
        public Nullable<int> AppliedAs { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public string ReligionName { get; set; }
        public Nullable<bool> HaveExperience { get; set; }
        public Nullable<int> AreaOfInterestID { get; set; }
        public string AreaOfInterestName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CatName { get; set; }
        public string OtherCityName { get; set; }
        public Nullable<int> SalutationID { get; set; }
        public string SalutationName { get; set; }
        public string OtherAreaName { get; set; }
        public string CVName { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<bool> WorkPermitYes { get; set; }
        public Nullable<bool> WorkPermitNo { get; set; }
        public string OtherDomicileCityName { get; set; }
        public string OtherPakistaniCityName { get; set; }
        public string Tehsil { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserStage { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<double> TotalExp { get; set; }
        public Nullable<double> Cement { get; set; }
        public Nullable<bool> CompensationFilled { get; set; }
    }
}
